// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWQetwsllLJcqZH-OxaFgJeDYWRHxaFA',
    appId: '1:194920093414:android:f4160743dd0ec839974d27',
    messagingSenderId: '194920093414',
    projectId: 'ubercloneuser-39a46',
    databaseURL: 'https://ubercloneuser-39a46-default-rtdb.firebaseio.com',
    storageBucket: 'ubercloneuser-39a46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9lsNBCbAdLR75cq6A8bIyjOc3TpWBeIc',
    appId: '1:194920093414:ios:e4dfdcaee823b00c974d27',
    messagingSenderId: '194920093414',
    projectId: 'ubercloneuser-39a46',
    databaseURL: 'https://ubercloneuser-39a46-default-rtdb.firebaseio.com',
    storageBucket: 'ubercloneuser-39a46.appspot.com',
    iosBundleId: 'com.example.driverapp',
  );
}
